### ISSUE TITLE
Crash report when even picking up the respective item that was configured to pe put in the custom slot

### ISSUE THREAD

**Issue by levilips123** [Thutmose/ThutWearables#3]
yea i cannot replicate the other one when putting the item in the slot because of this one:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Skillable-Mod-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 4/1/18 8:58 PM
Description: Ticking player

java.lang.NoSuchFieldError: CAPABILITY_ITEM_BAUBLE
	at thut.wearables.compat.baubles.Compat.onItemCapabilityAttach(Compat.java:58)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_Compat_onItemCapabilityAttach_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:599)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:85)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:641)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thut.wearables.compat.baubles.Compat.onItemCapabilityAttach(Compat.java:58)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_Compat_onItemCapabilityAttach_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:599)
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1216)
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:85)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 12
	Entity Name: flavius16
	Entity's Exact location: 12.52, 4.00, 14.87
	Entity's Block location: World: (12,4,14), Chunk: (at 12,0,14 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:641)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World--
	All players: 1 total; [EntityPlayerMP['flavius16'/12, l='New World--', x=12.52, y=4.00, z=14.87]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 230889991271160543
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:air;127;decoration
	Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2483 game time, 2483 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 19347 (now: false), thunder time: 34223 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 315515752 bytes (300 MB) / 1058275328 bytes (1009 MB) up to 1058275328 bytes (1009 MB)
	JVM Flags: 5 total; -Xmx1022M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version           | Source                                      | Signature                                |
	|:--------- |:--------------------- |:----------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2            | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp                   | 9.42              | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.1.2555      | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | aether_legacy         | 1.12.2-v2.0       | aether_legacy-1.12.2-v2.0.jar               | None                                     |
	| UCHIJAAAA | quark                 | r1.4-122          | Quark-r1.4-122.jar                          | None                                     |
	| UCHIJAAAA | skillable             | beta-9            | Skillable-Mod-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | autoreglib            | 1.3-15            | AutoRegLib-1.3-15.jar                       | None                                     |
	| UCHIJAAAA | baubles               | 1.5.0             | Baubles-Mod-1.12.jar                        | None                                     |
	| UCHIJAAAA | mantle                | 1.12-1.3.1.21     | Mantle-Mod-1.12.1.jar                       | None                                     |
	| UCHIJAAAA | bhc                   | 1.1.0b            | baubley-heart-canisters-1.12.2-1.1.0b.jar   | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| UCHIJAAAA | botania               | r1.10-349         | Botania r1.10-349.jar                       | None                                     |
	| UCHIJAAAA | cnoapm                | 1.0 by Dot_Silver | CEGA-1.12.jar                               | None                                     |
	| UCHIJAAAA | colytra               | 1.0.4.3           | colytra-1.12.2-1.0.4.3.jar                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | cosmeticarmorreworked | 1.12.2-v1         | CosmeticArmorReworked-1.12.2-v1.jar         | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | cucumber              | 1.0.3             | cucumber-1.12-1.0.3.jar                     | None                                     |
	| UCHIJAAAA | mocreatures           | 12.0.3            | DrZharks MoCreatures Mod-12.0.3.jar         | None                                     |
	| UCHIJAAAA | endercrop             | 1.12-1.3.4        | endercrop-1.12-1.3.4.jar                    | None                                     |
	| UCHIJAAAA | extraalchemy          | 0.3.6-release     | extraalchemy-0.3.6-release.jar              | None                                     |
	| UCHIJAAAA | forgelin              | 1.6.0             | Forgelin-1.6.0.jar                          | None                                     |
	| UCHIJAAAA | gottschcore           | 1.3.5             | GottschCore-mc1.12-f14.21.1.2387-v1.3.5.jar | None                                     |
	| UCHIJAAAA | harvestcraft          | 1.12.2a           | HarvestCraft-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | ironbackpacks         | 1.12.2-3.0.5-6    | IronBackpacks-1.12.2-3.0.5-6.jar            | None                                     |
	| UCHIJAAAA | jei                   | 4.8.0.114         | Just-Enough-Items-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | shadowmc              | 3.8.0             | ShadowMC-1.12-3.8.0.jar                     | None                                     |
	| UCHIJAAAA | leveluphp             | 1.1.1             | leveluphp-1.12.2-1.1.1.jar                  | None                                     |
	| UCHIJAAAA | lootbags              | 2.5.3b            | LootBags-1.12.2-2.5.3b.jar                  | None                                     |
	| UCHIJAAAA | cfm                   | 4.1.5             | MrCrayfishs-Furniture-Mod-1.12.1.jar        | None                                     |
	| UCHIJAAAA | mysticalagriculture   | 1.6.6             | mysticalagriculture-1.12-1.6.6.jar          | None                                     |
	| UCHIJAAAA | mysticalagradditions  | 1.2.7             | mysticalagradditions-1.12-1.2.7.jar         | None                                     |
	| UCHIJAAAA | petbat                | 1.4.7             | Pet-Bat-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | roguelike             | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar          | None                                     |
	| UCHIJAAAA | shulkerbox            | 1.3.0             | shulkerbox-1.3.0.jar                        | None                                     |
	| UCHIJAAAA | testdummy             | 1.12              | Test-Dummy-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | thut_wearables        | 3.1.6             | thut-wearables-1.12.2-3.1.6.jar             | None                                     |
	| UCHIJAAAA | torohealthmod         | 1.12.2-11         | torohealth-1.12.2-11.jar                    | None                                     |
	| UCHIJAAAA | toroquest             | 1.12.2-5.2        | toroquest-1.12.2-5.2.jar                    | None                                     |
	| UCHIJAAAA | totemessentials       | 1.1.0             | totemessentials-1.1.0.jar                   | None                                     |
	| UCHIJAAAA | twilightforest        | 3.5.263           | twilightforest-1.12.2-3.5.263-universal.jar | None                                     |
	| UCHIJAAAA | wearablebackpacks     | 3.1.2             | WearableBackpacks-1.12.2-3.1.2.jar          | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Skillable-Mod-1.12.2.jar)
  vazkii.skillable.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
ColytraLoadingPlugin (colytra-1.12.2-1.0.4.3.jar)
  c4.colytra.core.asm.ElytraTransformer
Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['flavius16'/12, l='New World--', x=12.52, y=4.00, z=14.87]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4590
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Thutmose** [comment]
Ahh, seems baubles has updated since I did the compatiblity, and the new baubles isn't compatible anymore, when I get time to work on this, I will see about updating the baubles compat to fix this.  This is the same cause as #2
